%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Medium Length Professional CV - RESUME CLASS FILE
%
% This template has been downloaded from:
% http://www.LaTeXTemplates.com
%
% This class file defines the structure and design of the template. 
%
% Original header:
% Copyright (C) 2010 by Trey Hunner
%
% Copying and distributing this file, with or without modification,
% is permitted in any medium without royalty, provided the copyright
% notice, and this notice is preserved. This file is offered as-is,
% without any warranty.
%
% Created by Trey Hunner and modified by www.LaTeXTemplates.com
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\ProvidesClass{resume}[2010/07/10 v0.9 Resume class]

\LoadClass[11pt,letterpaper]{article} % Font size and paper type

\usepackage[parfill]{parskip} % Remove paragraph indentation
\usepackage{array} % Required for boldface (\bf and \bfseries) tabular columns
\usepackage{ifthen} % Required for ifthenelse statements

\pagestyle{empty} % Suppress page numbers

%----------------------------------------------------------------------------------------
%	HEADINGS COMMANDS: Commands for printing name and address
%----------------------------------------------------------------------------------------

\def \name#1{\def\@name{#1}} % Defines the \name command to set name
\def \@name {} % Sets \@name to empty by default

\def \addressSep {$\diamond$} % Set default address separator to a diamond

% One, two or three address lines can be specified 
\let \@addressone \relax
\let \@addresstwo \relax
\let \@addressthree \relax

% \address command can be used to set the first, second, and third address (last 2 optional)
\def \address #1{
  \@ifundefined{@addresstwo}{
    \def \@addresstwo {#1}
  }{
  \@ifundefined{@addressthree}{
  \def \@addressthree {#1}
  }{
     \def \@addressone {#1}
  }}
}

% \printaddress is used to style an address line (given as input)
\def \printaddress #1{
  \begingroup
    \def \\ {\addressSep\ }
    \centerline{#1}
  \endgroup
  \par
  \addressskip
}

% \printname is used to print the name as a page header
\def \printname {
  \begingroup
    \hfil{\MakeUppercase{\namesize\bf \@name}}\hfil
    \nameskip\break
  \endgroup
}

%----------------------------------------------------------------------------------------
%	SECTION FORMATTING
%----------------------------------------------------------------------------------------

% Defines the rSection environment for the large sections within the CV
\newenvironment{rSection}[1]{ % 1 input argument - section name
  \sectionskip
  \MakeUppercase{\bf #1} % Section title
  \sectionlineskip
  \hrule % Horizontal line
  \begin{list}{}{ % List for each individual item in the section
    \setlength{\leftmargin}{1.5em} % Margin within the section
  }
  \item[]
}{
  \end{list}
}

%----------------------------------------------------------------------------------------
%	PRINT THE HEADING LINES
%----------------------------------------------------------------------------------------

\let\ori@document=\document
\renewcommand{\document}{
  \ori@document  % Begin document
  \printname % Print the name specified with \name
  \@ifundefined{@addressone}{}{ % Print the first address if specified
    \printaddress{\@addressone}}
  \@ifundefined{@addresstwo}{}{ % Print the second address if specified
    \printaddress{\@addresstwo}}
     \@ifundefined{@addressthree}{}{ % Print the third address if specified
    \printaddress{\@addressthree}}
}

%----------------------------------------------------------------------------------------
%	SUBSECTION FORMATTING
%----------------------------------------------------------------------------------------

\newenvironment{rSubsection}[4]{ % 4 input arguments - company name, year(s) employed, job title and location
 {\bf #1} \hfill {#2} \\ % Bold company name and date on the right
 \vspace{-1.5em}
 {\em #3} \hfill {\em #4} \\

}

\newenvironment{rSubsectionSmall}[2]{ % 2 input arguments 
 {\bf #1} \hfill {\em #2} \\ % Bold company name and date on the right
 \vspace{-1.5em}
}


\newenvironment{rSubsectionBullets}[4]{ % 4 input arguments - company name, year(s) employed, job title and location
 {\bf #1} \hfill {#2} \\ % Bold company name and date on the right
 {\em #3} \hfill {#4} \\ 
 \smallskip
  \begin{list}{$\cdot$}{\leftmargin=0em} % \cdot used for bullets, no indentation
   \itemsep -0.5em \vspace{-2em} % Compress items in list together for aesthetics
  }{
  \end{list}
  \vspace{0.5em} % Some space after the list of bullet points
}

%----------------------------------------------------------------------------------------
%	EDUCATION FORMATTING
%----------------------------------------------------------------------------------------

\newenvironment{edSubsectionMin}[4]{ % 4 input arguments - company name, year(s) employed, job title and location
 {\bf #1} \hfill {#2} \\ % Bold company name and date on the right
 {\em #4} \hfill {#3} \\
 \vspace{-1em}
}

\newenvironment{edSubsectionFull}[6]{
 {\bf #1} \hfill {#2} \\ % Bold company name and date on the right
 {\em #3} \hfill {\em #4} \\
{\em #6} \hfill  Supervisor: {#5} \\
 \vspace{-1em}
}

\newenvironment{edSubsectionHonours}[6]{
 {\bf #1} \hfill {#2} \\ % Bold company name and date on the right
 {\em #5} \hfill {#4} \\
 {#3} \hfill {#6} \\
 \vspace{-1em}
}

%----------------------------------------------------------------------------------------
%	TA SUBSECTION FORMATTING
%----------------------------------------------------------------------------------------

\newenvironment{taSubsectionMin}[4]{ % 4 input arguments - company name, year(s) employed, job title and location
	{\bf #1} \hfill {#2} \\ % Bold company name and date on the right
	{\em #3} \hfill {\em #4} \\
	\smallskip
	\vspace{-1.5em} % Some space after the list of bullet points
}

\newenvironment{taSubsectionNoInst}[3]{ % 3 input arguments - Course name, code, dates
	{\indent \quad \textbf{#1}} \hfill \\ % Bold company name and date on the right
	{\indent \qquad \em #2} \hfill {#3} \\
	\smallskip
	\vspace{-1.5em} % Some space after the list of bullet points
}

\newenvironment{taSubsectionNoInstDouble}[5]{ % 3 input arguments - Course name, code, dates
	{\indent \quad \textbf{#1}} \hfill \\ % Bold company name and date on the right
	{\indent \qquad \em #2} \hfill {#3} \\
	\smallskip
    {\indent \qquad \em #4} \hfill {#5} \\
	\smallskip
	\vspace{-1.5em} % Some space after the list of bullet points
}

\newenvironment{taSubsectionMinBullets}[4]{ % 4 input arguments - company name, year(s) employed, job title and location
 {\bf #1} \hfill {#2} % Bold company name and date on the right
 \ifthenelse{\equal{#3}{}}{}{ % If the third argument is not specified, don't print the job title and location line
  \\
  {\em #3} \hfill {\em #4} % Italic job title and location
  }\smallskip
  \begin{list}{$\cdot$}{\leftmargin=0em} % \cdot used for bullets, no indentation
   \itemsep -0.5em \vspace{-0.5em} % Compress items in list together for aesthetics
  }{
  \end{list}
  \vspace{0.5em} % Some space after the list of bullet points
}

\newenvironment{taSubsectionFull}[6]{ % 4 input arguments - company name, year(s) employed, job title and location
	{\bf #1} \hfill {#2} \\ % Bold company name and date on the right
	{\em #3} \hfill {\sc #4} \\ % Italic job title and location
	{\em #5} \hfill {\sc #6} \\ % Italic job title and location
	\smallskip
	\vspace{-1.5em} % Some space after the list of bullet points
}

\newenvironment{taSubsectionFullBullets}[6]{ % 4 input arguments - company name, year(s) employed, job title and location
 {\bf #1} \hfill {#2} % Bold company name and date on the right
 \ifthenelse{\equal{#3}{}}{}{ % If the third argument is not specified, don't print the job title and location line
  \\
  {\em #3} \hfill {\sc #4} \\ % Italic job title and location
  {\em #5} \hfill {\sc #6} % Italic job title and location
  }\smallskip
  \begin{list}{$\cdot$}{\leftmargin=0em} % \cdot used for bullets, no indentation
   \itemsep -0.5em \vspace{-0.5em} % Compress items in list together for aesthetics
  }{
  \end{list}
  \vspace{0.5em} % Some space after the list of bullet points
}


%----------------------------------------------------------------------------------------
%	PROJECTS FORMATTING
%----------------------------------------------------------------------------------------

\newenvironment{prSubsection}[4]{ % 4 input arguments - company name, year(s) employed, job title and location

 {\bf #1} \hfill {#2} \\ % Bold company name and date on the right
 {\em #3} \hfill {\em #4} \\

}


%----------------------------------------------------------------------------------------
%	AWARDS FORMATTING
%----------------------------------------------------------------------------------------

\newenvironment{aSubsection}[4]{ % 4 input arguments - company name, year(s) employed, job title and location
 {\bf #1} \hfill {#2} \\ % Bold company name and date on the right
 {\em #3} \hfill {\bf #4} \\
 \vspace{-1em}
}


% The below commands define the whitespace after certain things in the document - they can be \smallskip, \medskip or \bigskip
\def\namesize{\huge} % Size of the name at the top of the document
\def\addressskip{\smallskip} % The space between the two address (or phone/email) lines
\def\sectionlineskip{\medskip} % The space above the horizontal line for each section 
\def\nameskip{\bigskip} % The space after your name at the top
\def\sectionskip{\medskip} % The space after the heading section


%=============================================
%        Employment
%-=============================================

\newenvironment{employNoInst}[3]{ % 3 input arguments - Date, Title, supervisor(s)
	{\indent \quad \textbf{#1}} \hfill \textit{Supervised by:}\\ % Bold company name and date on the right
	{\indent \qquad \em #2} \hfill {#3} \\
	\smallskip
	\vspace{-1.5em} % Some space after the list of bullet points
}

\newenvironment{taSubsectionNoInstDouble}[5]{ % 3 input arguments - Course name, code, dates
	{\indent \quad \textbf{#1}} \hfill \textit{Supervised by:}\\ % Bold company name and date on the right
	{\indent \qquad \em #2} \hfill {#3} \\
	\smallskip
    {\indent \qquad \em #4} \hfill {#5} \\
	\smallskip
	\vspace{-1.5em} % Some space after the list of bullet points
}