name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  workflow_run:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Display the path
        run: echo $PATH
        shell: bash
        
      - name: Save ENV
        run: env > ENV.txt
        shell: bash
      
      - name: acpath
        run: echo "$GITHUB_ACTION_PATH" > gap.txt
        shell: bash
